### ISSUE TITLE
dist_common's family_size column in the DIVER database doesn't match the number of individuals therein

### ISSUE THREAD

**Issue by Viqsi** [MathematicalMedicine/DIVER#265]
This is something I ran into when trying to verify that I didn't break pedigree cohorts in the process of working on #236 and #261:

![image](https://github.com/user-attachments/assets/e5d9239f-f148-4610-887c-78345d85e47c)

For the "minimum pedigree size" constraint, pedigree ascertainment checks the `family_size` column. Yet there's only four individuals present. Out of 69932 distinct `fam_id`s in dist_common, the overwhelming majority have the same number of individuals present that `family_size` would indicate; only 889 have a mismatch (and of those 889, only one family - 49-190-126 - has MORE individuals present; the rest have fewer).
(I was able to determine that with the following query: `WITH baseline AS (SELECT fam_id, COUNT(ind_id) AS indcount, family_size FROM dist_common GROUP BY fam_id) SELECT * FROM baseline WHERE indcount != family_size;`)

@WValenti did some initial investigation and discovered that those `family_size` values are accurate in the DIGS database, but not in the DIVER database:

![image](https://github.com/user-attachments/assets/15cf1493-afa7-4cef-92d3-89e5e10c9a2e)

From here it evidently becomes a matter of rediscovering in the DIVER DB generation scripts why those individuals are kept out going from DIGS to DIVER, and whether or not/how `family_size` should be changed to match the actual total individual counts. That's in @WValenti's corner.

**Comment by Viqsi** [comment]
Issue is still current in db_edit 74. However, it's not a blocking issue (the workaround in pedigree ascertainment procs is still functioning), so I'm kicking the milestone down the road.

**Comment by WValenti** [comment]
Turned out this was only in DIVER/REVID dist_common because I hadn't updated ISI_data.dist_common_yyyymmddhh. Fixed that, but Jo has a workaround so it's not a big dea.
