### ISSUE TITLE
Move dist_dx_study back into equivalence_groups

### ISSUE THREAD

**Issue by WValenti** [MathematicalMedicine/DIVER#277]
-- Do this for DIGS, DIVER and REVID
INSERT INTO equivalence_groups SELECT * FROM DIGS.equivalence_groups WHERE first_member = 'dist_dx_study';
-- Do this for DIGS
DELETE FROM DIGS.equivalence_groups_PTPHI WHERE first_member = 'dist_dx_study';

**Comment by Viqsi** [comment]
No longer an issue in db_edit 74; closing.
